# -*- coding: cp936 -*-

#------------------
#	生成一个Ubuntu下的动态壁纸
#	使用方法：
#		1.	把该文件复制到壁纸文件夹
#		2.	运行
#		3.	sudo mv a.xml /usr/share/backgrounds/contest/trusty.xml
#------------------

import os
from random import shuffle

picture_dir = os.getcwd()
content = os.listdir(picture_dir)
content = [picture for picture in content if (picture[-4:] == '.jpg' or picture[-4:] == '.png')]
shuffle(content)

outf = open("a.xml", "w")
outf.write("<!-- Generated by kjkszpj's program -->")
outf.write("\
<background>\n\
  <starttime>\n\
    <year>2009</year>\n\
    <month>08</month>\n\
    <day>04</day>\n\
    <hour>00</hour>\n\
    <minute>00</minute>\n\
    <second>00</second>\n\
  </starttime>\n\
<!-- This animation will start at midnight. -->\n")

last = "";
for picture in content:
	if last != "":
		outf.write("  <transition>\n    <duration>5.0</duration>\n    <from>%s/%s</from>\n    <to>%s/%s</to>\n  </transition>\n" %(picture_dir, last, picture_dir, picture))
	outf.write("  <static>\n    <duration>1795.0</duration>\n    <file>%s/%s</file>\n  </static>\n" % (picture_dir, picture))
	last = picture

if (content != []):
	outf.write("  <transition>\n    <duration>5.0</duration>\n    <from>%s/%s</from>\n    <to>%s/%s</to>\n  </transition>\n" % (picture_dir, last, picture_dir, content[0]))
outf.write("</background>\n")
outf.close()
